[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python manage.py migrate && gunicorn config.wsgi --bind 0.0.0.0:$PORT"
healthcheckPath = "/api/health/"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
