# Generated by Django 6.1.1 on 2026-09-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_department_and_year'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('mc_number', ''), _negated=True), fields=('mc_number',), name='unique_nonempty_mc_number'),
        ),
    ]
