# Generated by Django 6.1.1 on 2026-09-09 06:36

from django.db import migrations, models


def backfill_message_channels(apps, schema_editor):
    Message = apps.get_model("communications", "Message")
    User = apps.get_model("accounts", "User")

    role_channels = {
        "ADMIN": "STUDENT_ADMIN",
        "DEAN": "STUDENT_DEAN",
        "OFFICIAL": "STUDENT_OFFICIAL",
        "STUDENT": "STUDENT_ADMIN",
    }

    for message in Message.objects.select_related("sender").iterator():
        if message.is_internal:
            message.channel = "STAFF_INTERNAL"
        else:
            sender_role = User.objects.filter(pk=message.sender_id).values_list(
                "role", flat=True
            ).first()
            message.channel = role_channels.get(sender_role, "STUDENT_ADMIN")
        message.save(update_fields=["channel"])


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='channel',
            field=models.CharField(choices=[('STUDENT_ADMIN', 'Student and Admin'), ('STUDENT_DEAN', 'Student and Dean'), ('STUDENT_OFFICIAL', 'Student and Official'), ('STAFF_INTERNAL', 'Staff internal')], default='STUDENT_ADMIN', max_length=30),
        ),
        migrations.RunPython(backfill_message_channels, migrations.RunPython.noop),
    ]
