export const placeholders = {
  username: "Enter username",
  email: "Enter user email",
  password: "Enter password",
  passwordConfirm: "Re-enter password",
  fullName: "Enter full name",
  phone: "Enter your number",
  mcNumber: "Enter MC number",
  cpmNumber: "Enter CPM number",
  incidentTitle: "Enter incident title",
  incidentDescription: "Enter incident description",
  location: "Enter location",
  searchIncidents: "Search by title or location",
  message: "Enter your message",
  note: "Enter a note",
  officialEmail: "Enter official email",
  verificationNote: "Enter verification note",
  rejectionReason: "Enter rejection reason",
  infoRequest: "Enter information request",
  assignmentComment: "Enter assignment instructions",
  closureNote: "Enter closure note",
  reopenReason: "Enter reason for additional work",
  progressNote: "Enter progress note",
  resolutionStatement: "Enter resolution statement",
} as const;
